// <auto-generated />
namespace Vertise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FollowerstoUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FollowerstoUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201409061813519_Followers to User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
