// <auto-generated />
namespace Vertise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class EntityMoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityMoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201409061958090_Entity Moved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
